### ISSUE TITLE
How do you add a file that will be loaded as a webpack external in index.html?

### ISSUE THREAD

**Issue by brainkim** [tomchentw/reacthtmlpack#18]
I'm trying to load pixi.js, but it's got it's own issues because of browserify transforms and other such nonsense. I want to use webpack externals with pixi.js and get a script tag of the built, unminified version in development and the built minified version in production, and have the public path resolve for both. Is this possible?

**Comment by tomchentw** [comment]
Not sure if I got it right, but check the `index.html.js` of `react-google-maps/examples/gh-pages` out here: 
http://git.io/v4Vw3

It grabs `prism.js` as a individual script tag so it could be loaded by `WebWorker` directly.

**Comment by brainkim** [comment]
Forgot to respond to this. That worked! Thanks!

**Comment by tomchentw** [comment]
Cool!!!! How do you like this package?

**Comment by brainkim** [comment]
It's been great! The interactives team at Vice is using reacthtmlpack to prototype server-less frontend things and it's faster to setup than anything else out there. It's an ideal fit for an interactive team b/c all we need to do in prod is put the assets behind a CDN. There are some upcoming projects where we need routing and maybe a server though so we might switch to something else; I actually spent a lot of today catching up on the all the insane 'webpack-redux-react-universal-isomorphic-starter-templates' out there and started despairing b/c refactoring an reacthtmlpack application to use one of those architectures might be kind of difficult.

Let me know if there's anything I can do to help! Been looking through the codebase to see if we can refactor reacthtmlpack to get routing/server-side-rendering. There's been a lot of fuss over the Christmas break about how js (and especially react) -related tooling has gotten too complex, and I think reacthtmlpack stands out as being one of the simplest and most elegant solutions.

Happy holidays and best of luck in 2016!
Brian

**Comment by tomchentw** [comment]
I'd love some ideas and support for getting static generated pages with routes work first. (Related to #5) I'm much more interested in I'm targeting:

* Single `index.html.js` file
* React-Router based application
* Each routes mapped to different pages
* Each pages are the combination of `index.html.js` and React-Router rendered result

By __Single `index.html.js` file__, that means
* Each pages will have the same set of css/js files, it's the application's responsibility to dynamically dispatch different styles for different pages
* Each page may contain different title/meta tags supported by react-helmet, but again the dispatch logic should exist in react-router application.

This allows us to build several static hosted pages with one react-router backed application. For example, company website, blog, personal website, library demo pages, library documentation pages……
